config/routes.rb
Blog::Application.routes.draw do
  root 'posts#index'
  devise_for :users
  resources :posts do
    resources :comments
    
    collection do
      get "archive"
      post 'tag'
    end
    
  end
  
  resources :tags
  
  resources :users

  

  

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :post_tags
  has_many :tags, through: :post_tags, dependent: :destroy #dependent destroy works for post_tags but not working for tags. Why is that?
  validates :title, presence: true, length: { minimum: 5 }
  belongs_to :user
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tags  
  has_many :posts, through: :post_tags
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #User has many posts and comments  
  has_many :posts
  has_many :comments
  
  def name 
    return first_name + ' ' + last_name
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :first_name
      devise_parameter_sanitizer.for(:sign_up) << :last_name
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]
 
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comments_params)
    @comment.user = current_user
    @comment.save
    redirect_to post_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end  
  
  def comments_params
    params.require(:comment).permit(:commenter, :body)
  end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :edit, :create, :update, :destroy]
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def archive
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
    @tags = Tag.all
    @tag = Tag.new
  end
  
  def tag
    @post_tag = PostTag.find(params[:tag_id])
    @post = Post.find(@post_tag.post_id)
    redirect_to @post
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  def index
    @posts = Post.order("created_at desc").limit(5)
    @tags = Tag.all
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  
  private
    def post_params
      params.require(:post).permit(:title, :text)
    end
    
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
    @tag = Tag.new
  end
  
  def create    
    @post = Post.find(params[:post_id])
    @tag = @post.tags.create(tag_params)
    redirect_to post_path(@post)
    
    #search all the tags in the system, is there a tag with this name?
    # if tag not found create a new tag if found use that tag
    # make a new post_tag objet that has the tag and post
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @tag = @post.tags.find(params[:id])
    @tag.destroy
    redirect_to post_path(@post)
  end
  
  def index
    @tags = Tag.order("name")
  end

  private
    def tag_params
      params.require(:tag).permit(:name)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end
  
  def index
    @users = User.order("first_name")
  end
  
  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.user.name %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Delete Comment', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
  <div class="form-group">
    <h4>
      <%= f.label :title %>
    </h4>
    <%= f.text_field :title, class: "form-control", placeholder: "Text input"%>
  </div>
 
  <div class="form-group">
    <h4><%= f.label :text %></h4>
    <%= f.text_area :text, class: "form-control", placeholder: "Text input" %>
  </div>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/archive.html.erb
<div class="container">
  <h1 class="text-success">Archives</h1>
  
  <%= link_to 'Back to Posts', posts_path, class: "text-success" %><br>

  <% @posts.each do |post| %>
    <p> 
      Created <%= post.created_at %>
      <br>
      Last Updated <%= post.updated_at %>
    </p>
    
    <p>
      <strong>Title:</strong>
      <%= post.title %>
    </p>

    <p>
      <strong>Text:</strong>
      <%= post.text %>
    </p>
    
    <p>    
      <%= link_to 'Show', post_path(post) %> |
      <%= link_to 'Edit', edit_post_path(post) %> |
      <%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>
  
  <%= link_to 'Back to Posts', posts_path, class: "text-success" %> | 
  <%= link_to 'To Top of Page', archive_posts_path, class: "text-success" %>
  
</div>

app/views/posts/edit.html.erb
<div class="container">
  <h1>Edit post</h1>
  <br> 
  
  <%= 'Author: ' + @post.user.name %>
  
  <%= render 'form' %>

  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>

<p>
  <% if user_signed_in? %>
    <%= 'Hello ' + current_user.name + ' | ' + current_user.email %> |
    <%= link_to( 'Sign out', destroy_user_session_path, {method: :delete} )%>
  <% else %>
    <p>
      Not Signed In? 
      <%= link_to( 'Sign in', new_user_session_path ) %>
    </p>
  <% end%>
</p>

<% if user_signed_in? %>
  <%= link_to 'New post', new_post_path, class: "btn btn-primary"%>
<% end %>  
<%= link_to 'Archives', archive_posts_path, class: "btn btn-success" %>

<table class="table table-hover">
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>    
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td><%= link_to 'Show', post_path(post) %></td>
      
      <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% else %>
        <td></td>
        <td></td>
      <% end %>
      
      
      
    </tr>
  <% end %>
</table>


<%# commented out block below using if false%>
<h4>Tags</h4>
<% @tags.each do |tag|%>
  <ul>
    <li><%= link_to tag.name, { action: 'tag', tag_id: tag.id }, { method: :post }%></li>  
  </ul>
<% end %>

app/views/posts/new.html.erb
<div class="container">
  <h1 class="text-primary">
    New Post
  </h1>
 
  <%= render 'form' %>
 
  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <br>
  <div>
    <%= 'Author: ' + @post.user.name %>
  </div>
  
  <div>
    <h3><strong>Title:</strong></h3>
    <p><%= @post.title %></p>
  </div>
 
  <div>
    <h3><strong>Text:</strong></h3>
    <p><%= @post.text %></p>
  </div>

   <%= link_to 'Edit Post', edit_post_path(@post) %> |
   <%= link_to 'Back to Posts', posts_path %>
   <br>
 
  <h3>Comments</h3>
  <%= render @post.comments %>

  <h3>Add a comment:</h3>
  <%= render "comments/form" %>
  <br>    
  <h3>Tags</h3>
  <%= render @post.tags %>

  <h3>Add Tags</h3>
  <%= render "tags/form" %>
  <br>
</div>

app/views/tags/_form.html.erb
<%= form_for @tag do |f| %>
  <p>
    <%= f.text_field :name %>
  </p>
  <%= f.submit%>
<% end %>

app/views/tags/_tag.html.erb
<li><%= link_to tag.name, { action: 'tag', tag_id: tag.id }, { method: :post }%> |
<%= link_to 'Remove Tag', [@post, tag], method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger" %></li>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
     <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h1>Edit User</h1>

  <%= render 'form' %>

  <%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<p>
  <% if user_signed_in? %>
    <%= 'Hello ' + current_user.name + ' | ' + current_user.email %>
    <%= link_to( 'Sign out', destroy, user_session_path, {method: :delete} )%>
    <% else %>
    <p>NOT SIGNED IN</p>
    <%= link_to( 'Log in', new_user_session_path ) %>
    <% end%>
</p>

<%= link_to 'New User', new_user_path, class: "btn btn-primary" %>
<%= link_to 'Posts', posts_path, class: "btn btn-info"%>
   
<table class="table table-hover">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user_path(user) %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<div class="container">
  <h1>New User</h1>

  <%= render 'form' %>

  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1>User Info</h1>
  <p>
    <strong>First Name:</strong>
    <%= @user.first_name %>
  </p>
  
  <p>
    <strong>Last Name:</strong>
    <%= @user.last_name %>
  </p>
  
  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
  
  <p>
    <strong>Password:</strong>
    <%= @user.password %>
  </p>
    
  <%= link_to 'Edit User', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
</div>